### ISSUE TITLE
[Bug] Package version range in latest README is incorrect

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_intercom#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Currently the version range of our latest version (v0.5.0) instructs users to install `[">=0.4.0", "<0.5.0"]`. This means if users follow our README then they will not get the latest version of the package.

We need to update our README to have the correct range, highlighted below:
```yml
packages:
  - package: fivetran/intercom
    version: [">=0.5.0", "<0.6.0"]
```

### Relevant error log or model output

```shell
N/A
```

### Expected behavior

Customers are instructed to install the latest version range of our package and not an older/out of date range.

### dbt Project configurations

N/A

### Package versions

v0.5.0

### What database are you using dbt with?

postgres

### dbt Version

N/A

### Additional Context

N/A

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
Closing as this was handled during the last migration.
