### ISSUE TITLE
When two events occur at the same time, they should be separated.

### ISSUE THREAD

**Issue by daniel-gonzalez-danu** [fivetran/dbt_intercom#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I have an issue with `conversation_part_history` table, sometimes when two events occur at the same time, they appear only in one row, for example, on the screenshot attached, when part_type is open, body should be null and the text in body column should be in a new row as a comment, it also occurs when part_type is assignment 

![Result](https://user-images.githubusercontent.com/122238548/235761765-493fb4dc-4185-470c-860e-2ece1f73aba4.png)
![assignment](https://user-images.githubusercontent.com/122238548/235763192-31eaeff2-9e48-41f0-a706-6b330f87a43b.png)

### Expected behavior

If these two events occur at the same time, I want them to be separated in different rows.

### dbt Project configurations

```
 intercom_database: fivetran
  intercom_schema: intercom
  intercom__using_team: False
  intercom__using_company_tags: False
```

### Package versions

```
packages:
  - package: fivetran/intercom
    version: [">=0.6.0", "<=0.7.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version

![dbt_version](https://user-images.githubusercontent.com/122238548/235764814-9c96d361-7739-4d14-8aa6-56e0cf91d4b8.png)

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @daniel-gonzalez-danu thanks for opening this issue! One quick question, is this question related to the source table and how Fivetran syncs the data, or regarding the output of the dbt_intercom dbt package models?

**Comment by daniel-gonzalez-danu** [comment]
Hi @fivetran-joemarkiewicz, thanks for your quick response, we think that is related to how Fivetran syncs and transforms the data

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the clarification. This repository is used for the dbt package transformations. As such, we won't be able to make any adjustments to how the data is synced in this repository. If you feel your request would best be applied to the synced data (pre transformation) then I would recommend opening a [support ticket](https://support.fivetran.com/hc/en-us) to inquire with our support team to understand the nature of the source data and the format it should be syncing in.

If an update is then applied to the connector, we can then look at making an appropriate adjustments in this project.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this ticket as this likely was related to the Fivetran connector sync. Please feel free to reopen if this was not the case. Thanks!
