### ISSUE TITLE
Add support for Intercom Events

### ISSUE THREAD

**Issue by dselman** [fivetran/dbt_intercom#8]
Within our Intercom setup we send custom events to Intercom. Any plans to update FiveTran and this package to support Intercom Events?

Reference:
https://developers.intercom.com/intercom-api-reference/reference#list-user-events

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dselman! While the Fivetran connector and dbt package do not support the Intercom Events object, we welcome you to open a [feature request](https://support.fivetran.com/hc/en-us/requests/new) ticket for the Intercom connector to support the Events object in the future.
